const poem = [
  { day: 1, english: "East wind thaws the ice", chinese: "东风解冻" },
  {
    day: 2,
    english: "Anew, we takeover the soil",
    chinese: "我们重新占领土地",
  },
  { day: 3, english: "Memory breaks into the earth", chinese: "记忆破入大地" },
  { day: 4, english: "To be held in this body", chinese: "被这具身体承载" },
  { day: 5, english: "The insects never listen", chinese: "昆虫从不倾听" },
  {
    day: 6,
    english: "Hibernating insects begin to stir",
    chinese: "蛰虫始振",
  },
  { day: 7, english: "Looking up at the Spring Moon", chinese: "仰望春月" },
  {
    day: 8,
    english: "A village wakes from its silence",
    chinese: "村庄从沉寂中醒来",
  },
  {
    day: 9,
    english: "I am thinking of my family",
    chinese: "我在想着我的家人",
  },
  { day: 10, english: "A tin of packed sardines", chinese: "一罐装沙丁鱼" },
  { day: 11, english: "Fish rise to the surface", chinese: "鱼陟负冰" },
  {
    day: 12,
    english: "Our bodies are heavy with ice",
    chinese: "我们的身体沉重如冰",
  },
  {
    day: 13,
    english: "Daybreak shoots through the mountaintops",
    chinese: "黎明穿透山巅",
  },
  {
    day: 14,
    english: "Listening to the ends of the earth",
    chinese: "聆听天涯尽头",
  },
  {
    day: 15,
    english: "A tree breathes new life into a sapling",
    chinese: "树为幼苗注入新生",
  },
  {
    day: 16,
    english: "Otters sacrifice fish as offerings",
    chinese: "獭祭鱼",
  },
  {
    day: 17,
    english: "Glassy eyes filled with lack",
    chinese: "透明的眼睛里充满匮乏",
  },
  {
    day: 18,
    english: "Birds carry food to feed their young",
    chinese: "鸟儿衔食喂养雏鸟",
  },
  {
    day: 19,
    english: "Rain peels open every wound",
    chinese: "雨剥开每一道伤口",
  },
  {
    day: 20,
    english: "A desire to flee the country",
    chinese: "想要逃离这个国家的欲望",
  },
  { day: 21, english: "Wild geese migrate north", chinese: "候雁北" },
  {
    day: 22,
    english: "A pattern of migration is justice",
    chinese: "迁徙的规律就是正义",
  },
  {
    day: 23,
    english: "Elderberries ripen with fervor",
    chinese: "接骨木果热烈地成熟",
  },
  {
    day: 24,
    english: "My continuous lust is a sin",
    chinese: "我不断的欲念是罪",
  },
  {
    day: 25,
    english: "A circle is a circle is a circle",
    chinese: "圆圈就是圆圈就是圆圈",
  },
  {
    day: 26,
    english: "Plants sprout and trees bud",
    chinese: "草木萌动",
  },
  {
    day: 27,
    english: "A sick boy sips pear tea in bed",
    chinese: "病男孩躺床啜梨茶",
  },
  {
    day: 28,
    english: "Flowers and bees suckle together",
    chinese: "花与蜂一同吸吮",
  },
  {
    day: 29,
    english: "His grandmother watches the downpour",
    chinese: "他的祖母注视着暴雨",
  },
  {
    day: 30,
    english: "A single peach split open on a picture",
    chinese: "画中一枚桃子裂开",
  },
  {
    day: 31,
    english: "Peach blossoms begin to bloom",
    chinese: "桃始华",
  },
  { day: 32, english: "The insects jitter and flit", chinese: "昆虫颤动飞掠" },
  {
    day: 33,
    english: "The grandfathers start to warble",
    chinese: "祖父们开始低吟",
  },
  {
    day: 34,
    english: "Their song a form of secrecy",
    chinese: "他们的歌是某种秘密",
  },
  { day: 35, english: "Antennae held in resonance", chinese: "触角保持共鸣" },
  { day: 36, english: "Orioles sing", chinese: "仓庚鸣" },
  {
    day: 37,
    english: "I crave the taste of his soft lips",
    chinese: "我渴望他柔唇的味道",
  },
  { day: 38, english: "Melody ringing", chinese: "旋律回响" },
  {
    day: 39,
    english: "My family denies my lips touching peach",
    chinese: "我的家人否认我吻过桃子",
  },
  {
    day: 40,
    english: "I crash back to earth as science experiment",
    chinese: "我像科学实验般重重坠回尘世",
  },
  { day: 41, english: "Eagles transform into doves", chinese: "鹰化为鸠" },
  {
    day: 42,
    english: "Neither warble, as they fly into Heaven",
    chinese: "他们飞向天堂时无声鸣唱",
  },
  {
    day: 43,
    english: "Two parents moving to a foreign country",
    chinese: "两位父母迁往异国",
  },
  {
    day: 44,
    english: "To become the dove, the eagle learns grace",
    chinese: "为成鸽，鹰学会了优雅",
  },
  {
    day: 45,
    english: "Eventually, the dove too will perish",
    chinese: "终有一天，鸽也会消逝",
  },
  { day: 46, english: "Swallows have arrived", chinese: "玄鸟至" },
  {
    day: 47,
    english: "I have circled and circled and circled",
    chinese: "我一圈又一圈地盘旋",
  },
  { day: 48, english: "Somber is lengthening", chinese: "忧郁在延长" },
  {
    day: 49,
    english: "Half the father, half the mother",
    chinese: "半是父亲，半是母亲",
  },
  {
    day: 50,
    english: "Inevitably, the sound of a heartbeat",
    chinese: "不可避免的心跳声",
  },
  {
    day: 51,
    english: "Thunder rumbles at the edge of the sky",
    chinese: "雷乃发声",
  },
  {
    day: 52,
    english: "A circle has circles in 阴 and 阳",
    chinese: "圆中有圆，含阴与阳",
  },
  {
    day: 53,
    english: "Money burns on top of tombstones",
    chinese: "纸钱在墓碑上燃烧",
  },
  {
    day: 54,
    english: "The push of a grandfather and his grandson",
    chinese: "祖父与孙子并肩的推动",
  },
  { day: 55, english: "I am waiting for a sign", chinese: "我在等待一个信号" },
  { day: 56, english: "First flashes of lightning", chinese: "始电" },
  { day: 57, english: "A kiss on the cheek", chinese: "脸颊上的一吻" },
  {
    day: 58,
    english: "Last taste of true memory",
    chinese: "对真实记忆的最后一尝",
  },
  {
    day: 59,
    english: "If I have never reached my potential,",
    chinese: "若我从未达到潜能，",
  },
  {
    day: 60,
    english: "Will I still be able to blossom?",
    chinese: "我还会开花吗？",
  },
  { day: 61, english: "Paulownia trees bloom", chinese: "桐始华" },
  { day: 62, english: "A single cloud surfaced", chinese: "一朵孤云浮现" },
  { day: 63, english: "Wintermelon seeds steam", chinese: "冬瓜籽蒸腾" },
  {
    day: 64,
    english: "It is time to resolve the air",
    chinese: "是时候理清空气了",
  },
  {
    day: 65,
    english: "I teeth at my fingers, a trail of blood",
    chinese: "我咬指尖，留下一线血痕",
  },
  { day: 66, english: "Field mice become quails", chinese: "田鼠化为鴽" },
  {
    day: 67,
    english: "Everything possesses the energy of another",
    chinese: "万物互具他者之能量",
  },
  { day: 68, english: "Quails become field mice", chinese: "鴽又化为田鼠" },
  {
    day: 69,
    english: "This too, hangs in perpetuity",
    chinese: "此亦长悬不止",
  },
  {
    day: 70,
    english: "So does family, in balance of a son",
    chinese: "家亦如此，在儿子的天平中维持",
  },
  { day: 71, english: "Rainbow first appears", chinese: "虹始见" },
  { day: 72, english: "Thin clouds blend together", chinese: "薄云相融" },
  { day: 73, english: "Spring Sun lazes", chinese: "春日懒散" },
  { day: 74, english: "The family holds the day", chinese: "一家人守住这日子" },
  {
    day: 75,
    english: "The possibility to shine is indefinite",
    chinese: "闪耀的可能无限",
  },
  { day: 76, english: "Duckweed begins to grow", chinese: "萍始生" },
  {
    day: 77,
    english: "Holding on to each other, like otters",
    chinese: "紧握彼此，如水獭相持",
  },
  { day: 78, english: "Children also grow", chinese: "孩子们也在成长" },
  {
    day: 79,
    english: "A family of four sits along the bund",
    chinese: "四口之家坐在堤岸旁",
  },
  {
    day: 80,
    english: "Watching the stars twinkle in sunlight",
    chinese: "看太阳下星星闪烁",
  },
  {
    day: 81,
    english: "Turtledoves flutter their wings",
    chinese: "候鸣鸠拂其羽",
  },
  { day: 82, english: "It is time to harvest", chinese: "到了收获的时节" },
  {
    day: 83,
    english: "We toughen our winged resolve",
    chinese: "我们锻炼有翼的决心",
  },
  {
    day: 84,
    english: "Grit teeth to pick plants",
    chinese: "咬紧牙关采摘植物",
  },
  {
    day: 85,
    english: "Darting between branches, they continue to labor",
    chinese: "他们在枝间穿梭，继续劳作",
  },
  {
    day: 86,
    english: "Hoopoes descend on mulberry trees",
    chinese: "戴胜降于桑",
  },
  {
    day: 87,
    english: "To spin silk into good fortune",
    chinese: "将丝缠成吉祥",
  },
  {
    day: 88,
    english: "Mother descends on child, urging him to study",
    chinese: "母亲俯身催促孩儿学习",
  },
  {
    day: 89,
    english: "The promise of a better and fruitful future",
    chinese: "对更好丰硕未来的承诺",
  },
  {
    day: 90,
    english: "He will never know that knowledge cannot save him",
    chinese: "他永远不会知道知识无法拯救他",
  },
  { day: 91, english: "Mole crickets chirp", chinese: "蝼蝈鸣" },
  {
    day: 92,
    english: "In rapid cries, notes of pure tone",
    chinese: "急促的鸣叫，纯净的音符",
  },
  {
    day: 93,
    english: "My grandmother crickets her feet",
    chinese: "祖母的脚像蛐蛐般作声",
  },
  {
    day: 94,
    english: "She soothes herself in the hot bath",
    chinese: "她在热浴中安抚自己",
  },
  {
    day: 95,
    english: "These are mole crickets, please call them so",
    chinese: "这些是土蝼蛄，请如此称呼它们",
  },
  { day: 96, english: "Earthworms emerge", chinese: "蚯蚓出；" },
  { day: 97, english: "A oval has more 阳 than 阴", chinese: "椭圆阳多于阴" },
  {
    day: 98,
    english: "The looming feeling of emergency",
    chinese: "紧迫感在逼近",
  },
  {
    day: 99,
    english: "The Summer Sun cracks the ground",
    chinese: "夏日烈阳龟裂大地",
  },
  {
    day: 100,
    english: "Shriveled bodies provide nutrients",
    chinese: "枯萎的身躯提供养分",
  },
  { day: 101, english: "Wild gourds grow", chinese: "王瓜生" },
  {
    day: 102,
    english: "We taste the summer squash, roasted with oil",
    chinese: "我们尝烤油煎的夏南瓜",
  },
  {
    day: 103,
    english: "A hidden guard prevents breaking out of certainty",
    chinese: "隐秘的守护阻止脱离确定性",
  },
  {
    day: 104,
    english: "Here, the pumpkins skinned with tender",
    chinese: "这里，南瓜被温柔剥皮",
  },
  {
    day: 105,
    english: "Here we kiss before the sweet",
    chinese: "在甜蜜之前我们相吻",
  },
  { day: 106, english: "Bitter herbs flourish", chinese: "苦菜秀" },
  {
    day: 107,
    english: "Hands dyed green from pulling stems",
    chinese: "拉着茎，双手被染成绿色",
  },
  {
    day: 108,
    english: "My mother steeps them into broth with other weeds",
    chinese: "我母亲把它们与其他野草一起煮成汤",
  },
  {
    day: 109,
    english: "She says bitterness cools the heart",
    chinese: "她说苦味能凉心",
  },
  {
    day: 110,
    english: "Even under water, my taste refuses to cool",
    chinese: "即便在水下，我的味觉也不肯冷却",
  },
  {
    day: 111,
    english: "Plants with tender branches begin to die",
    chinese: "靡草死",
  },
  {
    day: 112,
    english: "Ashy dust falls by the wayside",
    chinese: "灰尘在路旁落下",
  },
  {
    day: 113,
    english: "The sun beats on our nascent untanned chests",
    chinese: "阳光炙烤着我们初生未晒的胸膛",
  },
  {
    day: 114,
    english: "Carrying the glass, I taste his cheek",
    chinese: "捧着玻璃，我尝到他的面颊",
  },
  {
    day: 115,
    english: "It is smooth and filled with silk",
    chinese: "光滑而充满柔丝般的感觉",
  },
  {
    day: 116,
    english: "Our skin begins to form condensation",
    chinese: "我们的皮肤开始起出水珠",
  },
  { day: 117, english: "Wheat harvest arrives", chinese: "麦秋至" },
  {
    day: 118,
    english: "Windows swell within their frames",
    chinese: "窗户在框内微微膨胀",
  },
  {
    day: 119,
    english: "The kitchen glass fogs with longing",
    chinese: "厨房的玻璃因渴望而起雾",
  },
  {
    day: 120,
    english: "Even the fans complain in circles",
    chinese: "连风扇也在打圈抱怨",
  },
  {
    day: 121,
    english: "I learn to breathe through the scorch",
    chinese: "我学会在灼热中呼吸",
  },
  { day: 122, english: "Praying mantises hatch", chinese: "螳螂生" },
  {
    day: 123,
    english: "Green bodies flick under first thick of heat",
    chinese: "绿色的身影在最初的热浪下闪动",
  },
  {
    day: 124,
    english: "I watch their stillness become intention",
    chinese: "我看着它们的静止变成意向",
  },
  {
    day: 125,
    english: "My own waiting ripens with wheat",
    chinese: "我的等待与麦子一同成熟",
  },
  {
    day: 126,
    english: "A sharpness follows in the grasses",
    chinese: "锐利在草丛中随后出现",
  },
  { day: 127, english: "Quails begin to chirp", chinese: "鹃始鸣" },
  {
    day: 128,
    english: "A single note pierces the morning’s soft flesh",
    chinese: "一声音符刺破清晨的柔软",
  },
  {
    day: 129,
    english: "You once said silence was a kind of mercy",
    chinese: "你曾说沉默是一种慈悲",
  },
  {
    day: 130,
    english: "I measure the distance between us in birdsong",
    chinese: "我以鸟鸣来衡量我们之间的距离",
  },
  {
    day: 131,
    english: "On the branch, a single metallic glint",
    chinese: "枝头有一抹金属般的闪光",
  },
  { day: 132, english: "Mockingbirds fall silent", chinese: "反舌无声" },
  {
    day: 133,
    english: "The air thickens where their voices should be",
    chinese: "他们声音该在之处空气变得浑厚",
  },
  {
    day: 134,
    english: "Absence leans against my ribs",
    chinese: "缺席靠在我的肋间",
  },
  {
    day: 135,
    english: "A silence cannot be broken with the sound of silence",
    chinese: "沉默无法被沉默之声打破",
  },
  {
    day: 136,
    english: "I peel back the layers of my skin to discover what’s within",
    chinese: "我剥开皮层去发现内里",
  },
  { day: 137, english: "Deer shed their antlers", chinese: "鹿角解" },
  {
    day: 138,
    english: "The forests loosen their grip on what is no longer needed",
    chinese: "森林放开不再需要之物的执握",
  },
  {
    day: 139,
    english: "I, too, am an object in need of breaking",
    chinese: "我也是一个需要被打破的物体",
  },
  {
    day: 140,
    english: "The air is so full of voices",
    chinese: "空气里充满了声音",
  },
  {
    day: 141,
    english: "It feels impossible to hear the one that’s coming next",
    chinese: "似乎无法听见下一个将至的声音",
  },
  { day: 142, english: "Cicadas begin to sing", chinese: "蜩始鸣" },
  {
    day: 143,
    english: "A bug can produce so much song in its carapace",
    chinese: "甲壳中能容纳如此多的歌声",
  },
  {
    day: 144,
    english: "A hazy vignette is dampened by noise",
    chinese: "一幅朦胧的剪影被噪音淋湿",
  },
  {
    day: 145,
    english: "I remind myself of past lives to keep the memory",
    chinese: "我提醒自己前世以保存记忆",
  },
  {
    day: 146,
    english: "I walk along the forest and feel the crunch of grass",
    chinese: "我沿林而行，感受草的碎响",
  },
  {
    day: 147,
    english: "Picturing myself as a trunk, I have never stood so still",
    chinese: "想象自己为树干，我从未如此静立",
  },
  { day: 148, english: "Pinellia emerges", chinese: "半夏生" },
  {
    day: 149,
    english: "A form of both poison and medicine",
    chinese: "既是毒又是药的一种形态",
  },
  { day: 150, english: "A thin stem pierces the mud", chinese: "细茎刺穿泥土" },
  {
    day: 151,
    english: "I dig it up gently, like a confession",
    chinese: "我轻轻挖出它，如同忏悔",
  },
  {
    day: 152,
    english: "Everything contains so much possibility",
    chinese: "万物蕴含无限可能",
  },
  {
    day: 153,
    english: "Warm winds arrive",
    chinese: "温风至",
  },
  {
    day: 154,
    english: "Cicadas test their voices in the canopy",
    chinese: "蝉在林冠试探它们的嗓音",
  },
  {
    day: 155,
    english: "I remember the sound of envy",
    chinese: "我记得嫉妒的声音",
  },
  {
    day: 156,
    english: "The kitchen windows fogged with July",
    chinese: "厨房的窗在七月起雾",
  },
  {
    day: 157,
    english: "And somewhere, heat gathers itself",
    chinese: "某处，热气凝聚",
  },
  {
    day: 158,
    english: "Crickets take shelter in the walls",
    chinese: "蟋蜂居壁",
  },
  {
    day: 159,
    english: "The air inside holds its breath for nightfall",
    chinese: "屋内的空气屏息等候夜幕",
  },
  {
    day: 160,
    english: "My brother picked at the peeling paint of our hallway",
    chinese: "我兄弟剥着走廊剥落的油漆",
  },
  {
    day: 161,
    english: "In silence, the house could listen to us",
    chinese: "在沉默中，房子能倾听我们",
  },
  {
    day: 162,
    english: "The warm wind finds every crack",
    chinese: "暖风找到每一道缝隙",
  },
  { day: 163, english: "Young hawks learn to fly", chinese: "鹰始挚" },
  {
    day: 164,
    english: "Every updraft is a kind of permission",
    chinese: "每一股上升气流都是一种允许",
  },
  {
    day: 165,
    english: "My father asks me to sign his documents",
    chinese: "我父亲要我在他的文件上签字",
  },
  {
    day: 166,
    english: "He repeated flight-shaped words like prayers",
    chinese: "他反复念着飞行般的词，像祷言",
  },
  {
    day: 167,
    english: "I hold these words in my throat, like a rat",
    chinese: "我把这些话堵在喉中，如同一只老鼠",
  },
  {
    day: 168,
    english: "He stayed still while I continued to soar",
    chinese: "他保持静止，而我继续翱翔",
  },
  {
    day: 169,
    english: "Rotting grass gives rise to fireflies",
    chinese: "腐草为萤",
  },
  {
    day: 170,
    english: "Light lifted out of embers",
    chinese: "光从余烬中升起",
  },
  {
    day: 171,
    english:
      "My father caught them when he was younger, plucking them out of leaves",
    chinese: "父亲年少时抓过它们，从叶间摘出",
  },
  {
    day: 172,
    english: "They glow like the forget of an old promise",
    chinese: "它们发光，像旧誓言的遗忘",
  },
  {
    day: 173,
    english: "I let go before it burns me; they sink bank",
    chinese: "我在被灼伤前放手；它们沉回岸边",
  },
  {
    day: 174,
    english: "Heavy humidity saturates earth",
    chinese: "土润溽暑",
  },
  {
    day: 175,
    english: "The soil sweats; the body follows",
    chinese: "泥土出汗；身体随之潮湿",
  },
  {
    day: 176,
    english: "Nothing evaporates cleanly—a bead of salt stung",
    chinese: "没有什么能干净蒸散——一滴盐般刺痛",
  },
  {
    day: 177,
    english: "I hold my parents’ summers like blood in my chest",
    chinese: "我把父母的夏天像血般揣在胸中",
  },
  {
    day: 178,
    english: "My parents hold their parents like language in the air",
    chinese: "我的父母将他们的父母像语言般悬于空中",
  },
  {
    day: 179,
    english: "The air presses forward into night",
    chinese: "空气向夜色推进",
  },
  { day: 180, english: "Great rains may fall", chinese: "大雨行时" },
  {
    day: 181,
    english: "They come like confessions, without structure",
    chinese: "它们像忏悔而来，无章可循",
  },
  {
    day: 182,
    english: "The darkness of my father’s temper after he drinks",
    chinese: "父亲饮酒后的脾气之暗",
  },
  {
    day: 183,
    english: "The lightness of my mother’s rage without her family",
    chinese: "母亲的愤怒如此轻盈，却没有她的家人",
  },
  {
    day: 184,
    english: "The trees continue, their leaves shading new hues",
    chinese: "树木继续，叶片遮映新色",
  },
  { day: 185, english: "Cold wind arrives", chinese: "凉风至" },
  {
    day: 186,
    english: "The trees shake in anticipation",
    chinese: "树木颤动以示期待",
  },
  {
    day: 187,
    english: "The grandmother is so far away from my father",
    chinese: "祖母与我父亲相距甚远",
  },
  {
    day: 188,
    english: "He flies west to see her face",
    chinese: "他飞向西方去见她的面容",
  },
  {
    day: 189,
    english: "The reflection of the sun on dewdrops",
    chinese: "阳光在露珠上的倒影",
  },
  { day: 190, english: "White dew descends", chinese: "白露降" },
  {
    day: 191,
    english: "Dew beads like withheld apologies",
    chinese: "露珠如被抑留的歉意凝成",
  },
  {
    day: 192,
    english: "The fields glisten with a quiet I cannot swallow",
    chinese: "田野闪着我难以吞下的静谧",
  },
  {
    day: 193,
    english: "My father folds his summer clothes in perfect squares",
    chinese: "我父亲把夏衣折成完美的方块",
  },
  {
    day: 194,
    english: "A drop trembles on his palm, shivering with anticipation",
    chinese: "一滴水珠在他掌心颤动，因期待而战栗",
  },
  { day: 195, english: "Winter cicadas chirp", chinese: "寒蝉鸣" },
  {
    day: 196,
    english: "Their thin song slices through the early dusk",
    chinese: "它们稀薄的歌穿透早暮",
  },
  {
    day: 197,
    english: "I think of every message I never sent you",
    chinese: "我想起所有未曾寄给你的讯息",
  },
  {
    day: 198,
    english: "My mother braids her hair tighter, as if to brace herself",
    chinese: "母亲把头发编得更紧，像要给自己壮胆",
  },
  {
    day: 199,
    english:
      "The echo leaves a trail, reaching toward the hawk already circling ahead",
    chinese: "回声留下一道痕，伸向前方盘旋的鹰",
  },
  {
    day: 200,
    english: "Hawks hunt and display their prey",
    chinese: "鹰乃祭鸟",
  },
  {
    day: 201,
    english: "The sky sharpens into its truest blue",
    chinese: "天空锐利成最真实的蓝",
  },
  {
    day: 202,
    english: "A single feather drifts, indecisive",
    chinese: "一根羽毛飘落，犹豫不决",
  },
  {
    day: 203,
    english: "Can we believe that power requires spectacle?",
    chinese: "我们能相信权力需要场面吗？",
  },
  {
    day: 204,
    english: "Below the tree line, something rustles",
    chinese: "林下有什么窸窣",
  },
  {
    day: 205,
    english: "Heaven and earth are solemn",
    chinese: "天地始肃",
  },
  {
    day: 206,
    english: "We lower our voices, barely a whisper",
    chinese: "我们压低声音，几乎成耳语",
  },
  {
    day: 207,
    english: "My mother and father do not speak to each other",
    chinese: "我的母亲和父亲互不言语",
  },
  {
    day: 208,
    english: "Everything grows heavier, even the light",
    chinese: "一切变得更沉重，连光也如此",
  },
  {
    day: 209,
    english: "My grandmother smooths the tablecloth and places a bowl down",
    chinese: "我的祖母抚平桌布，放下一个碗",
  },
  {
    day: 210,
    english: "Quietly, she nods toward the rice plumping with soup",
    chinese: "她默默点头，看着汤中渐鼓的米粒",
  },
  { day: 211, english: "The grain ripens", chinese: "禾乃登" },
  {
    day: 212,
    english: "Golden, surely inevitable",
    chinese: "金黄，确然不可避免",
  },
  {
    day: 213,
    english: "My hands hover above the stalks, unsure of their own steadiness",
    chinese: "我的手悬在禾秆上，不确定自身是否稳固",
  },
  {
    day: 214,
    english: "A plane above the sound, the mix of 阳 and 阴",
    chinese: "有一架飞机在声上方，阳与阴交织其间",
  },
  {
    day: 215,
    english: "A season of harvesting demands no hesitation",
    chinese: "收获的季节不容犹豫",
  },
  {
    day: 216,
    english: "Somewhere inside me, a ripeness leans on the horizon",
    chinese: "在我内心深处，一种成熟正向着地平线倾斜",
  },
  { day: 217, english: "Wild geese arrive", chinese: "鸿雁来" },
  {
    day: 218,
    english: "Their calls carve long corridors across the sky",
    chinese: "它们的叫声在天空中划出长长的通道",
  },
  {
    day: 219,
    english: "Migration is a form of confession",
    chinese: "迁徙是一种忏悔",
  },
  {
    day: 220,
    english: "My breath fogs as I watch their arrowed flight",
    chinese: "我看着它们如箭的飞行，呼吸成雾",
  },
  {
    day: 221,
    english:
      "Their formation bends, as if making room for the ones returning south",
    chinese: "它们的队形弯曲，仿佛给返南者让路",
  },
  { day: 222, english: "Swallows return south", chinese: "玄鸟归" },
  {
    day: 223,
    english: "Their departure severs summer cleanly",
    chinese: "它们的离去割断了夏天的延续",
  },
  {
    day: 224,
    english: "My lips still taste of a cooling tea",
    chinese: "我嘴唇仍有未饮尽凉茶的余味",
  },
  {
    day: 225,
    english: "You left like this once—decisive, airborne, kind",
    chinese: "你曾这样离开——果断、腾空、温柔",
  },
  {
    day: 226,
    english: "Above the rooftops, the remaining birds gather food for storage",
    chinese: "屋顶上，剩余的鸟儿收集食物储藏",
  },
  { day: 227, english: "Birds storing food", chinese: "群鸟养羞" },
  {
    day: 228,
    english: "They tuck seeds between stones, under fallen leaves",
    chinese: "它们将种子塞在石间，落叶下",
  },
  {
    day: 229,
    english: "Instinct teaches them what to keep for later",
    chinese: "本能教会它们为未来保存什么",
  },
  {
    day: 230,
    english: "My mother preserves fruit until the jar glows amber",
    chinese: "母亲腌果，直到罐子泛着琥珀色",
  },
  {
    day: 231,
    english: "The sweetness thickens, waiting for thunder",
    chinese: "甜味变稠，等待雷声",
  },
  { day: 232, english: "Thunder begins to cease", chinese: "雷始收声" },
  {
    day: 233,
    english: "The sky finally exhales",
    chinese: "天空终于呼出一口气",
  },
  {
    day: 234,
    english: "Silence presses its cool cheek against my neck",
    chinese: "静默将凉意贴在我的颈侧",
  },
  {
    day: 235,
    english: "My father locks the windows before night settles",
    chinese: "夜幕降临前父亲锁上窗户",
  },
  {
    day: 236,
    english: "The stillness deepens with the sounds of insects",
    chinese: "寂静中夹杂着昆虫的鸣叫声",
  },
  {
    day: 237,
    english: "Hibernating insects seal their burrows",
    chinese: "蛰虫坯户",
  },
  {
    day: 238,
    english: "A soft scritch of dirt and intention",
    chinese: "泥土与意图的轻微刮擦声",
  },
  {
    day: 239,
    english: "Everything hides before it breaks",
    chinese: "一切在破碎前先行藏匿",
  },
  {
    day: 240,
    english: "I bury a letter I never sent beneath a sapling",
    chinese: "我把一封未寄的信埋在幼苗下",
  },
  {
    day: 241,
    english: "The roots, thirsty for winter, reach toward the drying riverbeds",
    chinese: "渴盼冬日的根伸向干涸的河床",
  },
  {
    day: 242,
    english: "Water sources begin to dry up",
    chinese: "水始涸",
  },
  {
    day: 243,
    english: "Stones shine where the currents once lived",
    chinese: "流水曾经的地方石头闪亮",
  },
  {
    day: 244,
    english: "I kneel to touch a river’s ribcage",
    chinese: "我跪下触摸河流的肋骨",
  },
  {
    day: 245,
    english: "A heron lifts itself into the thinning air",
    chinese: "苍鹭振翅进入稀薄的空气",
  },
  {
    day: 246,
    english: "Its wings beat a path toward the colder dew waiting ahead",
    chinese: "它的翅膀拍打出一条通向前方寒露的路",
  },
  {
    day: 247,
    english: "Wild geese arrive as guests",
    chinese: "鸿雁来宾",
  },
  {
    day: 248,
    english: "Their shadows flicker across harvested fields",
    chinese: "它们的影子在收割过的田野上闪烁",
  },
  {
    day: 249,
    english: "The air tastes metallic with change",
    chinese: "空气带着金属味的变迁",
  },
  {
    day: 250,
    english: "My hands ache from gathering what’s left",
    chinese: "我因收拾残余而手酸",
  },
  {
    day: 251,
    english: "A flock splits neatly",
    chinese: "一群鸟整齐分裂",
  },
  {
    day: 252,
    english: "Sparrows entering the water become clams",
    chinese: "雀入大水为蛤",
  },
  {
    day: 253,
    english: "The world folds into metaphor",
    chinese: "世界折叠为隐喻",
  },
  {
    day: 254,
    english: "A shell is only a wing learning stillness",
    chinese: "贝壳只是翅膀学习静止的模样",
  },
  {
    day: 255,
    english: "I picture myself inside a tidepool, waiting for release",
    chinese: "我想象自己在潮池中，等待释放",
  },
  {
    day: 256,
    english: "Even the chrysanthemums hesitate before blooming",
    chinese: "就连菊花在盛开前也会犹豫片刻",
  },
  {
    day: 257,
    english: "Chrysanthemums bloom with yellow flowers",
    chinese: "菊有黄花",
  },
  {
    day: 258,
    english: "Yellow mouths opening toward the cold",
    chinese: "黄色的花瓣向寒冷张开口",
  },
  {
    day: 259,
    english: "My grandmother arranges them on her altar, one by one",
    chinese: "祖母把它们一朵一朵摆在祭坛上",
  },
  {
    day: 260,
    english: "Every petal feels like a softened blade",
    chinese: "每瓣花瓣像被磨软的刀刃",
  },
  {
    day: 261,
    english: "Their scent lingers, pointing toward the frost",
    chinese: "它们的香气徘徊，指向即将降",
  },
  {
    day: 262,
    english: "Jackals offer prey to beasts",
    chinese: "豺乃祭兽",
  },
  {
    day: 263,
    english: "A single white breath escapes the brush",
    chinese: "一口白气从灌木间溢出",
  },
  {
    day: 264,
    english: "Predators practice their ancient ceremonies",
    chinese: "掠食者演练它们古老的仪式",
  },
  {
    day: 265,
    english: "I practice my own rituals of letting go",
    chinese: "我实践着自己的一套放手仪式。",
  },
  {
    day: 266,
    english: "Along the treeline, leaves yellow to their edges",
    chinese: "树线附近的树叶边缘都泛黄了",
  },
  {
    day: 267,
    english: "Plants and trees yellow and shed",
    chinese: "草木黄落",
  },
  {
    day: 268,
    english: "They fall without protest",
    chinese: "它们无声无息地飘落",
  },
  {
    day: 269,
    english: "A soft rain of endings",
    chinese: "一场柔软的终结之雨",
  },
  {
    day: 270,
    english: "My mother sweeps the path in slow, sure strokes",
    chinese: "母亲以缓慢而稳健的动作扫着小径",
  },
  {
    day: 271,
    english: "Each leaf curls inward, retreating toward the insects below",
    chinese: "每片叶子向内卷曲，退向下面的昆虫",
  },
  {
    day: 272,
    english: "Hibernating insects retreat underground",
    chinese: "蛰虫咸俯",
  },
  {
    day: 273,
    english: "Their bodies tuck into sleep, into safety",
    chinese: "它们的身体蜷入睡眠，进入安全",
  },
  {
    day: 274,
    english: "The soil seals behind them like a kiss",
    chinese: "它们身后的泥土像一个吻般封住了缝隙",
  },
  {
    day: 275,
    english: "I kneel to touch the earth, feeling its shallow warmth",
    chinese: "我跪下触摸泥土，感受浅浅的温热",
  },
  {
    day: 276,
    english: "Beneath my palm, winter’s first hush",
    chinese: "掌下，冬日的第一抹静默",
  },
  { day: 277, english: "Water starts to freeze", chinese: "水始冻" },
  {
    day: 278,
    english: "The first sheet forms like a held breath",
    chinese: "第一层冰如同屏住的呼吸形成",
  },
  {
    day: 279,
    english: "I kneel beside the pond, listening for cracks",
    chinese: "我跪在池塘边，听着裂纹声",
  },
  {
    day: 280,
    english: "A childhood memory surfaces: poking crabs with a stick",
    chinese: "一段童年记忆浮现：用棍子戳螃蟹。",
  },
  {
    day: 281,
    english: "The frost from autumn settles onto the glassy skin",
    chinese: "秋霜落在光滑如镜的表面",
  },
  { day: 282, english: "The earth begins to freeze", chinese: "地始冻" },
  {
    day: 283,
    english: "Footsteps thud with a new finality",
    chinese: "脚步声以新的决绝沉闷",
  },
  {
    day: 284,
    english: "Soil clumps like unsent messages",
    chinese: "土块如未寄出的信般成团",
  },
  {
    day: 285,
    english: "My brother tests the ground with his heel",
    chinese: "我哥哥用脚后跟试探地面",
  },
  {
    day: 286,
    english: "The ice beneath deepens, a darker mirror",
    chinese: "脚下冰层加厚，成更暗的镜面",
  },
  {
    day: 287,
    english: "Pheasants entering the ocean transform into clams",
    chinese: "雉入大水为蜃",
  },
  {
    day: 288,
    english: "Myth becomes shelter when logic thins",
    chinese: "当逻辑稀薄时，神话成了庇护",
  },
  {
    day: 289,
    english: "I imagine birds slipping into shells, carrying heat",
    chinese: "我想象鸟儿滑入贝壳，携着余温",
  },
  {
    day: 290,
    english: "Once, my father told me stories of lies and deceit",
    chinese: "父亲曾给我讲过一些关于谎言和欺骗的故事。",
  },
  {
    day: 291,
    english: "The mirror of ice thickens, holding its voice",
    chinese: "冰镜渐厚，抑制着它的声音",
  },
  {
    day: 292,
    english: "Rainbow become hidden from view",
    chinese: "虹藏不见",
  },
  {
    day: 293,
    english: "Colors retreat without acknowledgement",
    chinese: "色彩悄然退却",
  },
  {
    day: 294,
    english: "The sky folds into grayscale",
    chinese: "天空折叠成灰阶",
  },
  {
    day: 295,
    english: "I wrap a scarf twice around my neck",
    chinese: "我把围巾在脖子上绕两圈",
  },
  {
    day: 296,
    english: "The silence in the ice spreads to the air",
    chinese: "冰中的静默蔓延到空气里",
  },
  {
    day: 297,
    english: "Heaven’s energy rises, earth’s energy sinks",
    chinese: "天气上升，地气下降",
  },
  {
    day: 298,
    english: "Two movements that never touch",
    chinese: "永不相触的两股动向",
  },
  {
    day: 299,
    english: "A choreography of distance",
    chinese: "距离的舞蹈编排",
  },
  {
    day: 300,
    english: "I stand between them, unsure which of the measure",
    chinese: "我站在他们中间，不知该如何抉择",
  },
  {
    day: 301,
    english: "A thin crack begins in the ice, deliberate and slow",
    chinese: "冰上开始一道细裂，刻意而缓慢",
  },
  {
    day: 302,
    english: "Winter is formed by closure and blockage",
    chinese: "闭塞而成冬",
  },
  {
    day: 303,
    english: "Windows seal themselves in breath",
    chinese: "窗户在呼吸中自我封闭",
  },
  {
    day: 304,
    english: "My mother burns brushes to warm the house",
    chinese: "我母亲烧草来取暖",
  },
  {
    day: 305,
    english: "We sit and say little, a closeness of darkness",
    chinese: "我们静静地坐着，很少说话，黑暗笼罩着我们。",
  },
  {
    day: 306,
    english: "The crack widens, revealing darkness beneath",
    chinese: "裂缝扩阔，显露下方的黑暗",
  },
  { day: 307, english: "The pheasants are silent", chinese: "鹖鴠不鸣" },
  {
    day: 308,
    english: "The world swallows its own sound",
    chinese: "世界吞没了自身的声响",
  },
  {
    day: 309,
    english: "I remember arguments that ended without resolution",
    chinese: "我记得那些无解而散的争论",
  },
  {
    day: 310,
    english: "A reminder of the season of grief",
    chinese: "提醒大家，这是一个悲伤的季节",
  },
  {
    day: 311,
    english: "Snow piles along the crack, softening its edges",
    chinese: "雪在裂缝旁堆积，软化其边缘",
  },
  { day: 312, english: "Tigers begin to mate", chinese: "虎始交" },
  {
    day: 313,
    english: "Even ferocity seeks continuation",
    chinese: "连凶猛也寻求延续",
  },
  {
    day: 314,
    english: "Heat coils inside cold",
    chinese: "热在冷中盘绕",
  },
  {
    day: 315,
    english: "My father smokes near the open door",
    chinese: "父亲在开着的门旁点起烟",
  },
  {
    day: 316,
    english: "Snow drifts toward the warm air, dissolving instantly",
    chinese: "雪向暖气飘去，瞬间化开",
  },
  { day: 317, english: "Lychee tree emerges", chinese: "荔挺出" },
  {
    day: 318,
    english: "A winter bloom, stubborn and red",
    chinese: "一株冬花，顽强且赤红",
  },
  {
    day: 319,
    english: "I touch its petal, thin as regret",
    chinese: "我触摸它薄如悔恨的花瓣",
  },
  {
    day: 320,
    english: "My grandmother, in the factory, has never seen its beauty",
    chinese: "我的祖母在工厂工作，从未见过它的美。",
  },
  {
    day: 321,
    english: "A faint red reflection appears on the ice",
    chinese: "冰面上浮现淡淡的红色倒影",
  },
  { day: 322, english: "Earthworms curl up", chinese: "蚯蚓结" },
  {
    day: 323,
    english: "Even the smallest life folds into itself",
    chinese: "即便最微小的生命也向内折叠",
  },
  {
    day: 324,
    english: "I light a candle, watching wax shiver",
    chinese: "我点燃一支蜡烛，看蜡泪颤抖",
  },
  {
    day: 325,
    english: "My breath clouds the window like a lost map",
    chinese: "我的呼吸把窗雾成一张迷失的地图",
  },
  {
    day: 326,
    english: "The red reflection deepens, becoming a pulse",
    chinese: "红色倒影加深，变成脉动",
  },
  { day: 327, english: "Deer shed their horns", chinese: "麇角解" },
  {
    day: 328,
    english: "Release is a natural instinct",
    chinese: "释放是一种自然本能",
  },
  {
    day: 329,
    english: "The forest opens space for what is gone",
    chinese: "森林为已逝之物打开空间",
  },
  {
    day: 330,
    english: "I quash the candle and feel the room exhale",
    chinese: "我掐灭蜡烛，感觉房间呼出一口气",
  },
  {
    day: 331,
    english: "The pulse in the ice remains steady",
    chinese: "冰中的脉搏保持平稳",
  },
  {
    day: 332,
    english: "Spring water starts to flow",
    chinese: "水泉动",
  },
  {
    day: 333,
    english: "A faint gurgle beneath layers of stillness",
    chinese: "静谧层下隐约的汩汩声",
  },
  {
    day: 334,
    english: "Movement returns quietly, without spectacle",
    chinese: "运动悄然回归，无须喧嚣",
  },
  {
    day: 335,
    english: "I press my ear to the ground",
    chinese: "我贴耳于地",
  },
  {
    day: 336,
    english: "The pulse aligns with the sound of water waking",
    chinese: "脉动与苏醒的水声对齐",
  },
  { day: 337, english: "Geese migrate northward", chinese: "雁北乡" },
  {
    day: 338,
    english: "Deep in mourning, spring must always return",
    chinese: "即使在深深的哀悼中，春天也终将回归",
  },
  {
    day: 339,
    english: "Their formation sharpens against the pale dawn",
    chinese: "它们的队形在苍白的黎明中愈发清晰",
  },
  {
    day: 340,
    english: "I rehearse a conversation I may never have",
    chinese: "我排练一场或许永不会有的对话",
  },
  {
    day: 341,
    english: "The water’s movement nudges the pulse brighter",
    chinese: "水的流动推亮了脉搏",
  },
  { day: 342, english: "Magpies build their nest", chinese: "鹊始巢" },
  {
    day: 343,
    english: "Twigs arranged with deliberation",
    chinese: "细枝被刻意排列",
  },
  {
    day: 344,
    english: "My mother warms her hands above the stove",
    chinese: "母亲在炉火上温热双手",
  },
  {
    day: 345,
    english: "The brightness in the ice hints at thaw",
    chinese: "冰中的亮光暗示着融化",
  },
  { day: 346, english: "Pheasants start to crow", chinese: "雉雊" },
  {
    day: 347,
    english: "Their call muffled by the lingering cold",
    chinese: "它们的叫声被残留的寒冷闷住",
  },
  {
    day: 348,
    english: "Sound strains toward itself",
    chinese: "声音向自身用力伸展",
  },
  {
    day: 349,
    english: "I open the window a crack and taste the air",
    chinese: "我微开窗缝，品尝空气",
  },
  {
    day: 350,
    english: "The first drip of water falls along the crack",
    chinese: "第一滴水沿裂缝落下",
  },
  { day: 351, english: "Hens begin to brood", chinese: "鸡乳" },
  {
    day: 352,
    english: "A reminder of the cycle of life",
    chinese: "提醒我们生命的循环",
  },
  {
    day: 353,
    english: "I tuck extra blankets and circle myself",
    chinese: "我把额外的毯子裹紧自己",
  },
  {
    day: 354,
    english: "My father checks the thermostat twice",
    chinese: "父亲检查恒温器两次",
  },
  {
    day: 355,
    english: "Water threads along the ground",
    chinese: "水在地面上蜿蜒流淌",
  },
  { day: 356, english: "Birds of prey hunt swiftly", chinese: "征鸟厉疾" },
  {
    day: 357,
    english: "Survival sharpens to a point",
    chinese: "生存被磨尖到极点",
  },
  {
    day: 358,
    english: "The sky becomes a ledger of hunger",
    chinese: "天空成为饥饿的账册",
  },
  {
    day: 359,
    english: "I sip tea and feel my chest unclench",
    chinese: "我啜热茶，感到胸口松开",
  },
  {
    day: 360,
    english: "The water from the ice moves freely",
    chinese: "冰化的水流动的自由",
  },
  {
    day: 361,
    english: "The body of the marsh freezes solid",
    chinese: "水泽腹坚",
  },
  {
    day: 362,
    english: "Winter’s last act of consolidation",
    chinese: "冬之终固",
  },
  {
    day: 363,
    english: "All motion pauses before shifting again",
    chinese: "一切动作在再次转变前暂时停滞",
  },
  {
    day: 364,
    english: "I let the cold flatten my breath",
    chinese: "我让寒冷压平我的呼吸",
  },
  {
    day: 365,
    english: "Beneath my feet, the thaw waits, patient with its promise",
    chinese: "脚下，解冻等待着，耐心守着它的承诺",
  },
];

export default poem;
