const poem = [
  "East wind thaws the ice",
  "Anew, we takeover the soil",
  "Memory breaks into the earth",
  "To be held in this body",
  "The insects never listen",
  "Hibernating insects begin to stir",
  "Looking up at the Spring Moon",
  "A village wakes from its silence",
  "I am thinking of my family",
  "A tin of packed sardines",
  "Fish rise to the surface",
  "Our bodies are heavy with ice",
  "Daybreak shoots through the mountaintops",
  "Listening to the ends of the earth",
  "A tree breathes new life into a sapling",
  "Otters sacrifice fish as offerings",
  "Glassy eyes filled with lack",
  "Birds carry food to feed their young",
  "Rain peels open every wound",
  "A desire to flee the country",
  "Wild geese migrate north",
  "A pattern of migration is justice",
  "Elderberries ripen with fervor",
  "My continuous lust is a sin",
  "A circle is a circle is a circle",
  "Plants sprout and trees bud",
  "A sick boy sips pear tea in bed",
  "Flowers and bees suckle together",
  "His grandmother watches the downpour",
  "A single peach split open on a picture",
  "Peach blossoms begin to bloom",
  "The insects jitter and flit",
  "The grandfathers start to warble",
  "Their song a form of secrecy",
  "Antennae held in resonance",
  "Orioles sing",
  "I crave the taste of his soft lips",
  "Melody ringing",
  "My family denies my lips touching peach",
  "I crash back to earth as science experiment",
  "Eagles transform into doves",
  "Neither warble, as they fly into Heaven",
  "Two parents moving to a foreign country",
  "To become the dove, the eagle learns grace",
  "Eventually, the dove too will perish",
  "Swallows have arrived",
  "I have circled and circled and circled",
  "Somber is lengthening",
  "Half the father, half the mother",
  "Inevitably, the sound of a heartbeat",
  "Thunder rumbles at the edge of the sky",
  "A circle has circles in 阴 and 阳",
  "Money burns on top of tombstones",
  "The push of a grandfather and his grandson",
  "I am waiting for a sign",
  "First flashes of lightning",
  "A kiss on the cheek",
  "Last taste of true memory",
  "If I have never reached my potential,",
  "will I still be able to blossom?",
  "Paulownia trees bloom",
  "A single cloud surfaced",
  "Wintermelon seeds steam",
  "It is time to resolve the air",
  "I teeth at my fingers, a trail of blood",
  "Field mice become quails",
  "Everything possesses the energy of another",
  "Quails become field mice",
  "This too, hangs in perpetuity",
  "So does family, in balance of a son",
  "Rainbow first appears",
  "Thin clouds blend together",
  "Spring Sun lazes",
  "The family holds the day",
  "The possibility to shine is indefinite",
  "Duckweed begins to grow",
  "Holding on to each other, like otters",
  "Children also grow",
  "A family of four sits along the bund",
  "Watching the stars twinkle in sunlight",
  "Turtledoves flutter their wings",
  "It is time to harvest",
  "We toughen our winged resolve",
  "Grit teeth to pick plants",
  "Darting between branches, they continue to labor",
  "Hoopoes descend on mulberry trees",
  "To spin silk into good fortune",
  "Mother descends on child, urging him to study",
  "The promise of a better and fruitful future",
  "He will never know that knowledge cannot save him",
  "Mole crickets chirp",
  "In rapid cries, notes of pure tone",
  "My grandmother crickets her feet",
  "She soothes herself in the hot bath",
  "These are mole crickets, please call them so until",
  "Earthworms emerge",
  "A oval has more 阳 than 阴",
  "The looming feeling of emergency",
  "The Summer Sun cracks the ground",
  "Shriveled bodies provide nutrients",
  "Wild gourds grow",
  "We taste the summer squash, roasted with oil",
  "A hidden guard prevents breaking out of certainty",
  "Here, the pumpkins skinned with tender",
  "Here we kiss before the sweet",
  "Bitter herbs flourish",
  "Hands dyed green from pulling stems",
  "My mother steeps them into broth with other weeds",
  "She says bitterness cools the heart",
  "Even under water, my taste refuses to cool",
  "Plants with tender branches begin to die",
  "Ashy dust falls by the wayside",
  "The sun beats on our nascent untanned chests",
  "Carrying the glass, I taste his cheek",
  "It is smooth and filled with silk",
  "Our skin begins to form condensation",
  "Minor heat arrives",
  "Windows swell within their frames",
  "The kitchen glass fogs with longing",
  "Even the fans complain in circles",
  "I learn to breathe through the scorch",
  "Praying mantises hatch",
  "Green bodies flick under first thick of heat",
  "I watch their stillness become intention",
  "My own waiting ripens with wheat",
  "A sharpness follows in the grasses",
  "Shrikes begin to chirp",
  "A single note pierces the morning’s soft flesh",
  "You once said silence was a kind of mercy",
  "I measure the distance between us in birdsong",
  "On the branch, a single metallic glint",
  "Mockingbirds fall silent",
  "The air thickens where their voices should be",
  "Absence leans against my ribs",
  "A silence cannot be broken with the sound of silence",
  "I peel back the layers of my skin to discover what’s within",
  "Deer shed their antlers",
  "The forests loosen their grip on what is no longer needed.",
  "I, too, am trying to set something down",
  "The air is so full of voices",
  "It feels impossible to hear the one that’s coming next.",
  "Cicadas begin to sing",
  "A bug can produce so much song in its carapace",
  "A hazy vignette is dampened by noise",
  "I remind myself of past lives to keep the memory",
  "I walk along the forest and feel the crunch of grass",
  "Picturing myself as a trunk, I have never stood so still",
  "Pinellia emerges",
  "A form of both poison and medicine",
  "A thin stem pierces the mud",
  "I dig it up gently, like a confession",
  "Everything contains so much possibility",
  "Warm winds arrive, loosening the heavy green.",
  "Cicadas test their voices in the canopy.",
  "I remember the sound of stir fry.",
  "The kitchen windows fogged with July.",
  "And somewhere, heat gathers itself.",
  "Crickets take shelter in the walls.",
  "The air inside holds its breath for nightfall.",
  "My brother picked at the peeling paint of our hallway.",
  "In silence, the house could listen to us.",
  "The warm wind finds every crack.",
  "Young hawks learn to fly",
  "Every updraft is a kind of permission",
  "My father asks me to sign his documents",
  "He repeated flight-shaped words like prayers",
  "I hold these words in my throat, like a rat",
  "He stayed still while I continued to soar",
  "Rotting grass gives rise to fireflies",
  "Light lifted out of embers",
  "My father caught them when he was younger, plucking them out of leaves",
  "They glow like the forget of an old promise",
  "I let go before it burns me; they sink bank",
  "Heavy humidity saturates earth",
  "The soil sweats; the body follows.",
  "Nothing evaporates cleanly—a bead of salt stung.",
  "I hold my parents’ summers like blood in my chest.",
  "My parents hold their grandparents like language in the air.",
  "The air presses forward into night",
  "Great rains may fall",
  "They come like confessions, without structure",
  "The darkness of my father’s temper after he drinks",
  "The lightness of my mother’s aloofness without her husband",
  "The trees continue, their leaves shading new hues",
  "Cold wind arrives",
  "The trees shake in anticipation",
  "The grandmother is so far away from my father",
  "He flies west to see her face",
  "The reflection of the sun on dewdrops",
  "White dew descends",
  "Dew beads like withheld apologies.",
  "The fields glisten with a quiet I cannot swallow.",
  "My father folds his summer clothes in perfect squares.",
  "On his palm, a drop trembles—ready to answer the cold that’s coming.",
  "Winter cicadas cry out",
  "Their thin song slices through the early dusk.",
  "I think of every message I never sent you.",
  "My mother braids her hair tighter, as if to brace herself.",
  "The echo leaves a trail, reaching toward the hawk already circling ahead.",
  "Hawks hunt and display their prey",
  "The sky sharpens into its truest blue.",
  "A single feather drifts, indecisive.",
  "Can we believe that power requires spectacle?",
  "Below the tree line, something rustles—an entrance to solemnity.",
  "Heaven and earth begin to solemn",
  "We lower our voices, barely a whisper.",
  "My mother and father do not speak to each other",
  "Everything grows heavier, even the light.",
  "My grandmother smooths the tablecloth and places a bowl down.",
  "Quietly, she nods toward the rice plumping with soup.",
  "The grain ripens",
  "Golden, surely inevitable.",
  "My hands hover above the stalks, unsure of their own steadiness.",
  "A plane above the sound, the mix of 阳 and 阴",
  "A season of harvesting demands no hesitation.",
  "Somewhere inside me, a ripeness leans toward the geese on the horizon.",
  "Wild geese arrive",
  "Their calls carve long corridors across the sky.",
  "Migration is a form of confession.",
  "My breath fogs as I watch their arrowed flight.",
  "Their formation bends, as if making room for the ones returning south.",
  "Swallows return south",
  "Their departure severs summer cleanly.",
  "My lips still taste of a cooling tea I didn’t finish.",
  "You left like this once—decisive, airborne, kind.",
  "Above the rooftops, the remaining birds gather food for storage.",
  "Birds storing food",
  "They tuck seeds between stones, under fallen leaves.",
  "Instinct teaches them what to keep for later.",
  "My mother preserves fruit until the jar glows amber.",
  "The sweetness thickens, waiting for thunder to cease.",
  "Thunder begins to cease",
  "The sky finally exhales.",
  "Silence presses its cool cheek against my neck.",
  "My father locks the windows before night settles.",
  "The stillness deepens until even insects begin sealing their doors.",
  "Hibernating insects seal their burrows",
  "A soft scritch of dirt and intention.",
  "Everything hides before it breaks.",
  "I bury a letter I never sent beneath a sapling.",
  "The roots, thirsty for winter, reach toward the drying riverbeds.",
  "Water sources begin to dry up",
  "Stones shine where the currents once lived.",
  "I kneel to touch a river’s ribcage.",
  "A heron lifts itself into the thinning air.",
  "Its wings beat a path toward the colder dew waiting ahead.",
  "Wild geese arrive as guests",
  "Their shadows flicker across harvested fields.",
  "The air tastes metallic with change.",
  "My hands ache from gathering what’s left.",
  "A flock splits neatly—as if preparing for a transformation stranger than sparrows.",
  "Sparrows entering the water become clams",
  "The world folds into metaphor.",
  "A shell is only a wing learning stillness.",
  "I picture myself inside a tidepool, waiting for release.",
  "Even the chrysanthemums hesitate before showing yellow.",
  "Chrysanthemums bloom with yellow flowers",
  "Yellow mouths opening toward the cold.",
  "My grandmother arranges them on her altar, one by one.",
  "Every petal feels like a softened blade.",
  "Their scent lingers, pointing toward the frost preparing to descend.",
  "Jackals offer prey to beasts",
  "A single white breath escapes the brush.",
  "Predators practice their ancient ceremonies.",
  "I think of my own rituals of letting go.",
  "Somewhere near the treeline, leaves yellow to their edges.",
  "Plants and trees yellow and shed",
  "They fall without protest.",
  "A soft rain of endings.",
  "My mother sweeps the path in slow, sure strokes.",
  "Each leaf curls inward, retreating toward the insects below.",
  "Hibernating insects retreat underground",
  "Their bodies tuck into sleep, into safety.",
  "The soil seals behind them like a closing door.",
  "I kneel to touch the earth, feeling its shallow warmth.",
  "Beneath my palm, winter’s first hush begins to rise.",
  "Water starts to freeze",
  "The first sheet forms like a held breath",
  "I kneel beside the pond, listening for cracks",
  "A childhood memory surfaces: breaking ice with a stick",
  "The frost from autumn settles onto the glassy skin",
  "The earth begins to freeze",
  "Footsteps thud with a new finality",
  "Soil clumps like unsent messages",
  "My brother tests the ground with his heel",
  "The ice beneath deepens, a darker mirror",
  "Pheasants entering the ocean transform into clams",
  "Myth becomes shelter when logic thins",
  "I imagine birds slipping into shells, carrying heat",
  "My father once told me stories he didn’t believe",
  "The mirror of ice thickens, holding its own silence",
  "Rainbow become hidden from view",
  "Color withdraws without ceremony",
  "The sky folds into grayscale",
  "I wrap a scarf twice around my neck",
  "The silence in the ice spreads to the air",
  "Heaven’s energy rises, earth’s energy sinks",
  "Two movements that never touch",
  "A choreography of distance",
  "I stand between them, unsure which to follow",
  "A thin crack begins in the ice, deliberate and slow",
  "Winter is formed by closure and blockage",
  "Windows seal themselves in breath",
  "My mother burns ginger to warm the house",
  "We sit and say little, which is its own closeness",
  "The crack widens, revealing darkness beneath",
  "The pheasant is silent",
  "The world swallows its own sound",
  "I remember arguments that ended without resolution",
  "Grief, too, has its mute season",
  "Snow piles along the crack, softening its edges",
  "Tigers begin to mate",
  "Even ferocity seeks continuation",
  "Heat coils inside cold, hidden",
  "My father lights a cigarette near the open door",
  "Snow drifts toward the warm air, dissolving instantly",
  "Lychee tree grows",
  "A winter bloom, stubborn and red",
  "I touch its petal, thin as regret",
  "My grandmother said beauty in winter is a kind of defiance",
  "A faint red reflection appears on the ice",
  "Earthworms curl up",
  "Even the smallest life folds into itself",
  "I light a candle for no reason, watching wax shiver",
  "My breath clouds the window like a lost map",
  "The red reflection deepens, becoming a pulse",
  "Deer shed their horns",
  "Release is an ancient instinct",
  "The forest opens space for what is gone",
  "I turn off the candle and feel the room exhale",
  "The pulse in the ice remains steady",
  "Springs start to flow again",
  "A faint gurgle beneath layers of stillness",
  "Movement returns quietly, without spectacle",
  "I press my ear to the ground like a child",
  "The pulse aligns with the sound of water waking",
  "Geese migrate northward",
  "Even winter suggests a future",
  "Their formation sharpens against the pale dawn",
  "I rehearse a conversation I may never have",
  "The water’s movement nudges the pulse brighter",
  "Magpies build their nest",
  "Twigs arranged with deliberation",
  "My mother warms her hands above the stove",
  "The brightness in the ice hints at thaw",
  "Pheasants start to crow",
  "Their call muffled by the lingering cold",
  "Sound strains toward itself",
  "I open the window a crack and taste the air",
  "The first drip of meltwater falls along the crack",
  "Hens begin to brood",
  "Warmth gathers in unlikely places",
  "I tuck extra blankets around myself",
  "My father checks the thermostat twice",
  "The meltwater threads along the ground",
  "Birds of prey hunt swiftly",
  "Survival sharpens to a point",
  "The sky becomes a ledger of hunger",
  "I sip hot tea and feel my chest unclench",
  "The water from the ice moves more freely now",
  "The body of the marsh freeze solid",
  "Winter’s last act of consolidation",
  "All motion pauses before shifting again",
  "I stand outside and let the cold flatten my breath",
  "Beneath my feet, the thaw waits, patient with its promise",
];

export default poem;
